const {Schema}=require('mongoose');
const mongoose=require('mongoose');
const problemSchema=new Schema({
    title:{
        type:String,
        required:true,
    },
    description:{
        type:String,
        required:true, 
    },
    difficulty:{
        type:String,
        enum:['easy','medium','hard'],
        required:true,
    },
    tags:{
        type:String,
        enum:['array','string','math','dynamic programming','graph','tree','hash table','linked list','stack','queue','bit manipulation','greedy','sorting','recursion','sliding window'],
        required:true,
    },
    visibleTestCases:[
        {
            input:{
                type:String,
                required:true,
            },
            output:{
                type:String,
                required:true,
            },
            explanation:{
                type:String,
                required:true,
            }
        }
    ],
    startCode:[
        {
        language:{
            type:String,
            required:true,
        },
        completeCode:{
            type:String,
            required:true,
        }
    }
    ],
    referenceSolution:[
    {
        language:{
            type:String,
            required:true,
        },
        completeCode:{
            type:String,
            required:true,
        }
    }
    ],
    problemCreator:{
        type:Schema.Types.ObjectId,
        required:true,
        ref:'User'
    },
})

const Problem=mongoose.model('Problem',problemSchema);
module.exports=Problem;